spring:
  application:
    name: inference4j-showcase
  datasource:
    url: jdbc:h2:mem:chinook
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    async:
      request-timeout: 300000
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB

inference4j:
  nlp:
    text-classifier:
      enabled: false
  vision:
    text-detector:
      enabled: false
  audio:
    speech-recognizer:
      enabled: false
    vad:
      enabled: false

showcase:
  model-cache:
    idle-timeout: 10m
